# The final YAML runs PR trigger builds
trigger:
  branches:
    exclude:
     - master
pr:
  branches:
    include:
      - master
    exclude:
      - release

### Test on latest Windows and .Net version

jobs:
- job: WindowsBuild
  displayName: 'Build on Windows (sln)'
  pool:
    vmImage: 'windows-2022'

  variables:
    solution: 'OpenBVE.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - pwsh: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToAdd = @(
          "Microsoft.Net.Component.4.6.1.SDK",
          "Microsoft .NET Framework 4.6.1 Targeting Pack"
        )
        [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        if ($process.ExitCode -eq 0)
        {
            Write-Host "components have been successfully added"
        }
        else
        {
            Write-Host "components were not installed"
            exit 1
        }

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

- job: AppleMakeBuild
  displayName: 'Build on Apple OS-X (makefile)'
  pool:
    vmImage: 'macos-10.15'

  variables:
    solution: 'OpenBVE.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1
### Default Mono version isn't high enough on this OS-X image so kick to the latest
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_8_0
  - script: make publish 

### Linux makefile build
### This runs on the latest Mono version installed

- job: LinuxMakeBuild
  displayName: 'Build on Linux (makefile)'
  pool:
    vmImage: 'ubuntu-18.04'

  variables:
    solution: 'OpenBVE.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1
  - script: make publish